// Generated by CoffeeScript 1.3.3
(function() {
  var buildPath, def, getWeather, http, opts;

  http = require('http');

  opts = {
    hostname: 'api.openweathermap.org'
  };

  def = '';

  exports.defaults = function(cfg) {
    var i, n, objs;
    objs = [];
    for (i in cfg) {
      n = cfg[i];
      objs.push("" + i + "=" + n);
    }
    return def = objs.join('&');
  };

  exports.find = function() {};

  exports.now = function(cfg, cb) {
    opts.path = "/data/2.5/weather?" + (buildPath(cfg));
    console.log(opts.path);
    return getWeather(opts, function(json) {
      json.weather[0].iconUrl = "http://openweathermap.org/img/w/" + json.weather[0].icon + ".png";
      return cb(json);
    });
  };

  exports.forecast = function(cfg, cb) {
    opts.path = "/data/2.5/forecast?" + (buildPath(cfg));
    console.log(opts.path);
    return getWeather(opts, function(json) {
      return cb(json);
    });
  };

  exports.daily = function(cfg, cb) {
    opts.path = "/data/2.5/forecast/daily?" + (buildPath(cfg));
    console.log(opts.path);
    return getWeather(opts, function(json) {
      var item, _i, _len, _ref;
      _ref = json.list;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        item.weather[0].iconUrl = "http://openweathermap.org/img/w/" + item.weather[0].icon + ".png";
      }
      return cb(json);
    });
  };

  buildPath = function(cfg) {
    var i, n, objs;
    objs = [];
    for (i in cfg) {
      n = cfg[i];
      objs.push("" + i + "=" + n);
    }
    return "" + def + "&" + (objs.join('&'));
  };

  getWeather = function(opts, cb) {
    return http.get(opts, function(res) {
      var buffer;
      buffer = new Buffer(0);
      res.on('readable', function() {
        return buffer = Buffer.concat([buffer, this.read()]);
      });
      return res.on('end', function() {
        return cb(JSON.parse(buffer.toString('utf8')));
      });
    });
  };

}).call(this);
